FROM harbor.local/react-app/biller-simulator-json:bun-base AS base
WORKDIR /usr/src/app

FROM base AS build
COPY --chown=bun:bun . .
RUN bun run build

FROM nginx:alpine AS deploy
COPY --from=build /usr/src/app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/nginx.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
