FROM --platform=linux/amd64 harbor.local/react-app/biller-simulator-json:bun-base AS base
WORKDIR /usr/src/app

FROM base AS build
COPY . .
RUN bun run build

FROM --platform=linux/amd64 harbor.local/lib/nginx:alpine AS deploy
COPY --from=build /usr/src/app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
