import type { Iso8583FieldKind } from "./pack-iso8583";

export interface SituationalCatalogItem {
  readonly bit: number;
  readonly defaultValue?: string;
  readonly description: string;
  readonly kind: Iso8583FieldKind;
  readonly length: number;
  readonly name: string;
}

export const SITUATIONAL_CATALOG: readonly SituationalCatalogItem[] = [
  {
    bit: 14,
    name: "Expiration date",
    kind: "n",
    length: 4,
    description: "Card expiration date in YYMM format.",
    defaultValue: "2512",
  },
  {
    bit: 15,
    name: "Settlement date",
    kind: "n",
    length: 4,
    description: "Date when settlement occurs in MMDD format.",
    defaultValue: "0101",
  },
  {
    bit: 18,
    name: "Merchant type / MCC",
    kind: "n",
    length: 4,
    description:
      "4-digit classification code (MCC) describing the merchant's type of business.",
    defaultValue: "6011",
  },
  {
    bit: 22,
    name: "Point of service data code",
    kind: "n",
    length: 12,
    description:
      "Terminal capability, entry mode, PIN capture capability, and operational environment.",
    defaultValue: "021001000000",
  },
  {
    bit: 25,
    name: "Point of service condition code",
    kind: "n",
    length: 2,
    description:
      "Identifies specific conditions present at transaction location (00=Normal, 08=Mail/Phone, etc.).",
    defaultValue: "00",
  },
  {
    bit: 32,
    name: "Acquiring institution ID",
    kind: "llvar",
    length: 11,
    description: "Identification code of the acquiring financial institution.",
    defaultValue: "112",
  },
  {
    bit: 33,
    name: "Forwarding institution ID",
    kind: "llvar",
    length: 11,
    description:
      "Identification code of the institution routing or forwarding the message.",
    defaultValue: "112",
  },
  {
    bit: 37,
    name: "Retrieval reference number",
    kind: "ans",
    length: 12,
    description:
      "Unique key assigned by acquirer for tracking and retrieval throughout the life of transaction.",
    defaultValue: "000000000001",
  },
  {
    bit: 38,
    name: "Approval code",
    kind: "ans",
    length: 6,
    description: "Authorization or approval code generated by the issuer.",
    defaultValue: "123456",
  },
  {
    bit: 39,
    name: "Response code",
    kind: "ans",
    length: 2,
    description:
      "Result of transaction authorization request (00=Approved, 05=Do not honor, etc.).",
    defaultValue: "00",
  },
  {
    bit: 41,
    name: "Card acceptor terminal ID",
    kind: "ans",
    length: 8,
    description: "Unique identifier of the terminal at the merchant location.",
    defaultValue: "TERM0001",
  },
  {
    bit: 42,
    name: "Card acceptor ID code",
    kind: "ans",
    length: 15,
    description:
      "Unique merchant identifier assigned by the acquiring institution.",
    defaultValue: "000000000000000",
  },
  {
    bit: 43,
    name: "Card acceptor name / location",
    kind: "ans",
    length: 40,
    description:
      "Merchant business name and address (street, city, country code).",
    defaultValue: "MERCHANT TEST 01          YOGYAKARTA IDN",
  },
  {
    bit: 48,
    name: "Additional data - private",
    kind: "lllvar",
    length: 999,
    description:
      "BPD DIY proprietary private data elements or biller invoice references.",
    defaultValue: "",
  },
  {
    bit: 52,
    name: "Personal identification number (PIN) data",
    kind: "ans",
    length: 16,
    description:
      "Encrypted PIN block formatted in hexadecimal format (16 hex chars / 8 bytes).",
    defaultValue: "0000000000000000",
  },
  {
    bit: 53,
    name: "Security related control info",
    kind: "n",
    length: 16,
    description:
      "Security parameters used for key management and PIN encryption.",
    defaultValue: "1000000000000000",
  },
  {
    bit: 54,
    name: "Additional amounts",
    kind: "lllvar",
    length: 120,
    description:
      "Ledger balance, available balance, or fee amounts for account inquiry.",
    defaultValue: "",
  },
  {
    bit: 55,
    name: "Integrated circuit card (ICC) data",
    kind: "lllvar",
    length: 999,
    description: "EMV chip TLV tags passed during chip card transactions.",
    defaultValue: "",
  },
  {
    bit: 60,
    name: "Reserved private data",
    kind: "lllvar",
    length: 999,
    description: "Terminal batch number or switch transaction control data.",
    defaultValue: "",
  },
  {
    bit: 61,
    name: "Reserved private data",
    kind: "lllvar",
    length: 999,
    description: "Branch code, channel type, or biller product code.",
    defaultValue: "",
  },
  {
    bit: 62,
    name: "Reserved private data",
    kind: "lllvar",
    length: 999,
    description: "Custom invoice number or bill payment reference.",
    defaultValue: "",
  },
  {
    bit: 63,
    name: "Reserved private data",
    kind: "lllvar",
    length: 999,
    description: "Network management or proprietary auxiliary payload.",
    defaultValue: "",
  },
  {
    bit: 70,
    name: "Network management information code",
    kind: "n",
    length: 3,
    description:
      "Sign-on (001), Sign-off (002), Echo test (301), Cutover (201).",
    defaultValue: "001",
  },
  {
    bit: 90,
    name: "Original data elements",
    kind: "n",
    length: 42,
    description:
      "MTI, STAN, transmission date, and acquirer of original message.",
    defaultValue: "020000000101010000000000000000000000000000",
  },
  {
    bit: 100,
    name: "Receiving institution ID",
    kind: "llvar",
    length: 11,
    description: "Identification of the ultimate receiving institution.",
    defaultValue: "112",
  },
  {
    bit: 102,
    name: "Account identification 1",
    kind: "llvar",
    length: 28,
    description: "Source account number (Savings, Checking, or Loan).",
    defaultValue: "",
  },
  {
    bit: 103,
    name: "Account identification 2",
    kind: "llvar",
    length: 28,
    description: "Destination account number for fund transfers.",
    defaultValue: "",
  },
  {
    bit: 106,
    name: "Reserved private data",
    kind: "lllvar",
    length: 999,
    description: "Extended transaction or reversal reference.",
    defaultValue: "",
  },
  {
    bit: 120,
    name: "Reserved private data",
    kind: "lllvar",
    length: 999,
    description: "Biller validation result or customer inquiry breakdown.",
    defaultValue: "",
  },
  {
    bit: 123,
    name: "Reserved private data",
    kind: "lllvar",
    length: 999,
    description: "Delivery channel identification or merchant classification.",
    defaultValue: "",
  },
  {
    bit: 127,
    name: "Reserved private data",
    kind: "lllvar",
    length: 999,
    description: "Switching network private data or host routing tags.",
    defaultValue: "",
  },
  {
    bit: 128,
    name: "Message authentication code (MAC)",
    kind: "ans",
    length: 16,
    description:
      "Secondary cryptographic check value (8 bytes / 16 hex characters).",
    defaultValue: "",
  },
];
